/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerPlaceholderRouteImport } from './routes/seeker/placeholder'
import { Route as RecruiterHomepageRouteImport } from './routes/recruiter/homepage'
import { Route as RecruiterDiscoverRouteImport } from './routes/recruiter/discover'
import { Route as GeneralSignUpRouteImport } from './routes/general/sign-up'
import { Route as GeneralSignInRouteImport } from './routes/general/sign-in'
import { Route as GeneralLandingPageRouteImport } from './routes/general/landing-page'
import { Route as GeneralCreateProfileRouteImport } from './routes/general/create-profile'
import { Route as AuthSettingsRouteImport } from './routes/auth/settings'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as RecruiterJobsIndexRouteImport } from './routes/recruiter/jobs/index'
import { Route as RecruiterJobsIdRouteImport } from './routes/recruiter/jobs/$id'
import { Route as ChatJobIdCandidateIdRouteImport } from './routes/chat/$jobId.$candidateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerPlaceholderRoute = SeekerPlaceholderRouteImport.update({
  id: '/seeker/placeholder',
  path: '/seeker/placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterHomepageRoute = RecruiterHomepageRouteImport.update({
  id: '/recruiter/homepage',
  path: '/recruiter/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDiscoverRoute = RecruiterDiscoverRouteImport.update({
  id: '/recruiter/discover',
  path: '/recruiter/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralSignUpRoute = GeneralSignUpRouteImport.update({
  id: '/general/sign-up',
  path: '/general/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralSignInRoute = GeneralSignInRouteImport.update({
  id: '/general/sign-in',
  path: '/general/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralLandingPageRoute = GeneralLandingPageRouteImport.update({
  id: '/general/landing-page',
  path: '/general/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralCreateProfileRoute = GeneralCreateProfileRouteImport.update({
  id: '/general/create-profile',
  path: '/general/create-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/auth/settings',
  path: '/auth/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsIndexRoute = RecruiterJobsIndexRouteImport.update({
  id: '/recruiter/jobs/',
  path: '/recruiter/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsIdRoute = RecruiterJobsIdRouteImport.update({
  id: '/recruiter/jobs/$id',
  path: '/recruiter/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatJobIdCandidateIdRoute = ChatJobIdCandidateIdRouteImport.update({
  id: '/chat/$jobId/$candidateId',
  path: '/chat/$jobId/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/general/create-profile': typeof GeneralCreateProfileRoute
  '/general/landing-page': typeof GeneralLandingPageRoute
  '/general/sign-in': typeof GeneralSignInRoute
  '/general/sign-up': typeof GeneralSignUpRoute
  '/recruiter/discover': typeof RecruiterDiscoverRoute
  '/recruiter/homepage': typeof RecruiterHomepageRoute
  '/seeker/placeholder': typeof SeekerPlaceholderRoute
  '/chat/$jobId/$candidateId': typeof ChatJobIdCandidateIdRoute
  '/recruiter/jobs/$id': typeof RecruiterJobsIdRoute
  '/recruiter/jobs/': typeof RecruiterJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/general/create-profile': typeof GeneralCreateProfileRoute
  '/general/landing-page': typeof GeneralLandingPageRoute
  '/general/sign-in': typeof GeneralSignInRoute
  '/general/sign-up': typeof GeneralSignUpRoute
  '/recruiter/discover': typeof RecruiterDiscoverRoute
  '/recruiter/homepage': typeof RecruiterHomepageRoute
  '/seeker/placeholder': typeof SeekerPlaceholderRoute
  '/chat/$jobId/$candidateId': typeof ChatJobIdCandidateIdRoute
  '/recruiter/jobs/$id': typeof RecruiterJobsIdRoute
  '/recruiter/jobs': typeof RecruiterJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/general/create-profile': typeof GeneralCreateProfileRoute
  '/general/landing-page': typeof GeneralLandingPageRoute
  '/general/sign-in': typeof GeneralSignInRoute
  '/general/sign-up': typeof GeneralSignUpRoute
  '/recruiter/discover': typeof RecruiterDiscoverRoute
  '/recruiter/homepage': typeof RecruiterHomepageRoute
  '/seeker/placeholder': typeof SeekerPlaceholderRoute
  '/chat/$jobId/$candidateId': typeof ChatJobIdCandidateIdRoute
  '/recruiter/jobs/$id': typeof RecruiterJobsIdRoute
  '/recruiter/jobs/': typeof RecruiterJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/register'
    | '/auth/settings'
    | '/general/create-profile'
    | '/general/landing-page'
    | '/general/sign-in'
    | '/general/sign-up'
    | '/recruiter/discover'
    | '/recruiter/homepage'
    | '/seeker/placeholder'
    | '/chat/$jobId/$candidateId'
    | '/recruiter/jobs/$id'
    | '/recruiter/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/register'
    | '/auth/settings'
    | '/general/create-profile'
    | '/general/landing-page'
    | '/general/sign-in'
    | '/general/sign-up'
    | '/recruiter/discover'
    | '/recruiter/homepage'
    | '/seeker/placeholder'
    | '/chat/$jobId/$candidateId'
    | '/recruiter/jobs/$id'
    | '/recruiter/jobs'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/register'
    | '/auth/settings'
    | '/general/create-profile'
    | '/general/landing-page'
    | '/general/sign-in'
    | '/general/sign-up'
    | '/recruiter/discover'
    | '/recruiter/homepage'
    | '/seeker/placeholder'
    | '/chat/$jobId/$candidateId'
    | '/recruiter/jobs/$id'
    | '/recruiter/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  GeneralCreateProfileRoute: typeof GeneralCreateProfileRoute
  GeneralLandingPageRoute: typeof GeneralLandingPageRoute
  GeneralSignInRoute: typeof GeneralSignInRoute
  GeneralSignUpRoute: typeof GeneralSignUpRoute
  RecruiterDiscoverRoute: typeof RecruiterDiscoverRoute
  RecruiterHomepageRoute: typeof RecruiterHomepageRoute
  SeekerPlaceholderRoute: typeof SeekerPlaceholderRoute
  ChatJobIdCandidateIdRoute: typeof ChatJobIdCandidateIdRoute
  RecruiterJobsIdRoute: typeof RecruiterJobsIdRoute
  RecruiterJobsIndexRoute: typeof RecruiterJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/placeholder': {
      id: '/seeker/placeholder'
      path: '/seeker/placeholder'
      fullPath: '/seeker/placeholder'
      preLoaderRoute: typeof SeekerPlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/homepage': {
      id: '/recruiter/homepage'
      path: '/recruiter/homepage'
      fullPath: '/recruiter/homepage'
      preLoaderRoute: typeof RecruiterHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/discover': {
      id: '/recruiter/discover'
      path: '/recruiter/discover'
      fullPath: '/recruiter/discover'
      preLoaderRoute: typeof RecruiterDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general/sign-up': {
      id: '/general/sign-up'
      path: '/general/sign-up'
      fullPath: '/general/sign-up'
      preLoaderRoute: typeof GeneralSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general/sign-in': {
      id: '/general/sign-in'
      path: '/general/sign-in'
      fullPath: '/general/sign-in'
      preLoaderRoute: typeof GeneralSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general/landing-page': {
      id: '/general/landing-page'
      path: '/general/landing-page'
      fullPath: '/general/landing-page'
      preLoaderRoute: typeof GeneralLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general/create-profile': {
      id: '/general/create-profile'
      path: '/general/create-profile'
      fullPath: '/general/create-profile'
      preLoaderRoute: typeof GeneralCreateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/settings': {
      id: '/auth/settings'
      path: '/auth/settings'
      fullPath: '/auth/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs/': {
      id: '/recruiter/jobs/'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof RecruiterJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs/$id': {
      id: '/recruiter/jobs/$id'
      path: '/recruiter/jobs/$id'
      fullPath: '/recruiter/jobs/$id'
      preLoaderRoute: typeof RecruiterJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$jobId/$candidateId': {
      id: '/chat/$jobId/$candidateId'
      path: '/chat/$jobId/$candidateId'
      fullPath: '/chat/$jobId/$candidateId'
      preLoaderRoute: typeof ChatJobIdCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  GeneralCreateProfileRoute: GeneralCreateProfileRoute,
  GeneralLandingPageRoute: GeneralLandingPageRoute,
  GeneralSignInRoute: GeneralSignInRoute,
  GeneralSignUpRoute: GeneralSignUpRoute,
  RecruiterDiscoverRoute: RecruiterDiscoverRoute,
  RecruiterHomepageRoute: RecruiterHomepageRoute,
  SeekerPlaceholderRoute: SeekerPlaceholderRoute,
  ChatJobIdCandidateIdRoute: ChatJobIdCandidateIdRoute,
  RecruiterJobsIdRoute: RecruiterJobsIdRoute,
  RecruiterJobsIndexRoute: RecruiterJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
